server:
  port: 8086
spring:
  application:
    name: nihongo-user-service
  datasource:
    url: jdbc:mysql://onehost-amdcloudhn022602.000nethost.com:3306/tsezwyvdhosting_nihongo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tsezwyvdhosting_nihongo_app
    password: thuThuy@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com
  model: gemini-3.1-flash-lite

jwt:
  secret: "U7tjRTsx0baZLsRhHGcc0FA/B7MJ65IfQ0jZHvUyYrE="