server:
  port: 8086
spring:
  application:
    name: nihongo-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/nihongo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: thuthuyda1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/nihongo

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka